# Generated by Django 4.1.7 on 2023-05-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mainImage',
            field=models.FileField(default='default.png', upload_to=''),
        ),
    ]
